# File: .github/workflows/git-deploy.yml
name: Deploy to Server
on:
  push:
    branches:
      - master  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          
      - name: Push to Server
        run: |
          git remote add production ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PORT }}/home3/akiluvco/github/ai.shoppingarena.net
          git push production master
